package ar.com.dgarcia.objectmapper.api.ensemble.disassembly;

/**
 * This type represents a single instruction to get a part from a complex object (in order to disassemble it)
 * Created by kfgodel on 20/11/14.
 */
public interface DisassemblyInstruction {
    /**
     * @return The name of the parts generated by this instruction
     */
    String getPartName();

    /**
     * Extracts a part from the instance according to this instruction
     * @param instance The instance to get the part from
     * @return The extracted value
     */
    Object getPartFrom(Object instance);
}
